import { ModuleEnum } from 'src/common/enum/module.enum';
import { RoleType } from 'src/common/enum/role.enum';

export const RolePermissionData: {
  role: RoleType;
  module: ModuleEnum;
  isCreate: boolean;
  isRead: boolean;
  isUpdate: boolean;
  isDelete: boolean;
}[] = [
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.PRODUCT,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.USER,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.CATEGORY,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.ORDER,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.VOUCHER,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.CHATBOT,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },
  {
    role: RoleType.ADMIN,
    module: ModuleEnum.LOCATION,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: true,
  },

  {
    role: RoleType.USER,
    module: ModuleEnum.PRODUCT,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.USER,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.CATEGORY,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.ORDER,
    isCreate: true,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.VOUCHER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.CHATBOT,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.USER,
    module: ModuleEnum.LOCATION,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },

  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.PRODUCT,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.USER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.CATEGORY,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.ORDER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.VOUCHER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.CHATBOT,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.PRODUCT_MANAGER,
    module: ModuleEnum.LOCATION,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },

  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.PRODUCT,
    isCreate: false,
    isRead: false,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.USER,
    isCreate: false,
    isRead: false,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.CATEGORY,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.ORDER,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.VOUCHER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.CHATBOT,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.ORDER_MANAGER,
    module: ModuleEnum.LOCATION,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },

  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.PRODUCT,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.USER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.CATEGORY,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.ORDER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.VOUCHER,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.CHATBOT,
    isCreate: true,
    isRead: true,
    isUpdate: true,
    isDelete: false,
  },
  {
    role: RoleType.TECHNICIAN,
    module: ModuleEnum.LOCATION,
    isCreate: false,
    isRead: true,
    isUpdate: false,
    isDelete: false,
  },
];
