export enum MimeType {
  imageJPG = 'image/jpeg',
  imageJPEG = 'image/jpg',
  imagePJPEG = 'image/pjpeg',
  imagePNG = 'image/png',
  imageXPNG = 'image/x-png',
  imageGIF = 'image/gif',
  imageWEBP = 'image/webp',
  imageSVG = 'image/svg+xml',
  imageBMP = 'image/bmp',
  imageXWindowsBMP = 'image/x-windows-bmp',
  imageTIFF = 'image/tiff',
  imageXTIFF = 'image/x-tiff',
  imageICON = 'image/x-icon',
  imageMSIcon = 'image/vnd.microsoft.icon',
  imageHEIC = 'image/heic',
  imageHEIF = 'image/heif',
  imageHEICSequence = 'image/heic-sequence',
  imageHEIFSequence = 'image/heif-sequence',
  imageAVIF = 'image/avif',
}
