version: '3.9'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - database
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5433:5432'

  redis:
    image: redis:7-alpine # redis 8.0-rc1 chưa ổn định, nên dùng redis 7
    container_name: redis_db
    ports:
      - '6379:6379'
