version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    env_file:
      - .env.production
    expose:
      - '8080'
    depends_on:
      - database
      - redis
    networks:
      - web

  database:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env.production
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  redis:
    image: redis:8.0-rc1-alpine
    container_name: redis
    ports:
      - '6378:6379'
    networks:
      - web

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - web

networks:
  web:

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
